name: Generate and Commit Cache

on:
  schedule:
    - cron: '0 0/1 * * *'
  workflow_dispatch:

jobs:
  generate_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Program
        run: './gradlew build'
      - name: Generate Cache File
        if: ${{ success() }}
        run: 'java -jar ./build/libs/AwayFromAuction-Cache-1.0.jar'
        env:
          HYPIXEL_API_KEY: ${{ secrets.HYPIXEL_API_KEY }}
      - name: Commit Cache File
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: './docs/usernames.json'
          message: 'Automated - Updated Username Cache'
          author_name: 'SadieBot'
          author_email: '70802939+SadieBot@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
